### ISSUE TITLE
compatibility with redmine 5.0x

### ISSUE THREAD

**Issue by SinghNanak** [everlabs/project-roles-listing#1]

**Comment by OlegPasko** [comment]
@nanaksingh13, thanks for the report!
Please look to see if it's fixed with the last update.
https://github.com/everlabs/project_roles_listing/pull/2

**Comment by nanaksingh13** [comment]
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `PluginGemfile`: You cannot specify the same gem twice with different version requirements.
You specified: deface (>= 0) and deface (= 1.6.2). Bundler cannot continue.

 #  from C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_base_deface/PluginGemfile:3
 #  -------------------------------------------
 #  # bug described here: https://www.redmine.org/issues/35430
 >  gem 'deface', '1.6.2'
 #  # Later version of the Deface gem may not be fully compatible with Rails 5.2 & Redmine 4.2
 #  -------------------------------------------
. Bundler cannot continue.

 #  from C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/Gemfile:119
 #  -------------------------------------------
 #    eval_gemfile file
 >  end
 #  source 'https://rubygems.org'
 #  -------------------------------------------

**Comment by SinghNanak** [comment]
```
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `PluginGemfile`: You cannot specify the same gem twice with different version requirements.
You specified: deface (>= 0) and deface (= 1.6.2). Bundler cannot continue.

 #  from C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_base_deface/PluginGemfile:3
 #  -------------------------------------------
 #  # bug described here: https://www.redmine.org/issues/35430
 >  gem 'deface', '1.6.2'
 #  # Later version of the Deface gem may not be fully compatible with Rails 5.2 & Redmine 4.2
 #  -------------------------------------------
. Bundler cannot continue.

 #  from C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/Gemfile:119
 #  -------------------------------------------
 #    eval_gemfile file
 >  end
 #  source 'https://rubygems.org'
 #  -------------------------------------------
```

**Comment by OlegPasko** [comment]
Thanks for the details @nanaksingh13 
It should work now with the latest update.

**Comment by SinghNanak** [comment]
```
C:\Bitnami\redmine-5.0.3-0\apps\redmine\htdocs>bundle exec rake redmine:plugins RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- patches/add_safety_attributes_patch
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/project_roles_listing/init.rb:1:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `load'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `run_initializer'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `each'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `block in load'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by OlegPasko** [comment]
@nanaksingh13 , one more try, please :)

**Comment by SinghNanak** [comment]
@OlegPasko Migration is working but Redmine crashes

**Comment by ANKLV** [comment]
@nanaksingh13 could you please clarify with what error Redmine crashes? Have you successfully completed all the steps from the instructions?
